# indices.py
# Paste your full index members into the triple-quoted blobs below.
# This parser will:
#  - Uppercase everything
#  - Replace '.' with '-' (e.g., BRK-B, BF-B)
#  - Remove extra spaces / stray punctuation
#  - Dedupe while preserving order

import re
from typing import List

def _parse_blob(blob: str) -> List[str]:
    tokens = re.split(r'[^A-Z0-9\.-]+', blob.upper())
    out, seen = [], set()
    for t in tokens:
        t = t.strip()
        if not t:
            continue
        t = t.replace(".", "-")
        t = re.sub(r"-+", "-", t)     # collapse repeated dashes
        t = t.strip("-")              # trim leading/trailing dashes
        if not t:
            continue
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out

# ---------------- S&P 500 ----------------
SP500_LIST = _parse_blob("""
MMM,AOS,ABT,ABBV,ACN,ATVI,ADM,ADBE,ADP,AAP,ADI,ANSS,AFL,A,APD,AKAM,ALK,ALB,ARE,ALGN,ALLE,LNT,ALL,GOOGL,GOOG,MO,AMZN,AMCR,AEE,AAL,
AEP,AXP,AIG,AMT,AWK,AMP,ABC,AME,AMGN,APH,ADI,ANET,ANSS,ANTM,AON,AOS,APA,AAPL,AMAT,APTV,ADM,ARD,ANSS,ATO,ADSK,ADP,AZO,AVB,AVY,BKR,BLL,
BAC,BK,BAX,BDX,BRK.B,BBY,BIO,BIIB,BLK,BK,BA,BKNG,BWA,BXP,BSX,BMY,AVGO,BR,BRO,BF.B,CHRW,COG,CDNS,CPB,COF,CAH,KMX,CCL,CARR,CTLT,CAT,CBOE,
CBRE,CDW,CE,CNC,CNP,CDNS,CF,CRL,SCHW,CHTR,CVX,CMG,CB,CHD,CI,CMS,KO,CTVA,CL,CLX,CME,CMCSA,CMA,CAG,COP,ED,COO,CPRT,GLW,CTVA,COST,COTY,CCI,
CSX,CMI,CVS,DHI,DHR,DRI,DVA,DE,DAL,XRAY,DVN,DXCM,FANG,DLR,DFS,DISCA,DISCK,DISH,DG,DLTR,D,DPZ,DOV,DOW,DTE,DUK,DRE,DD,DXC,EMN,ETN,EBAY,ECL,
EIX,EW,EA,EMR,ETR,EOG,EFX,EQIX,EQR,ESS,EL,ETSY,RE,EXC,EXPE,EXPD,EXR,XOM,FFIV,FB,FAST,FRT,FDX,FIS,FISV,FLT,FMC,F,FTNT,FTV,FBHS,FOXA,FOX,
BEN,FCX,GPS,GRMN,IT,GD,GE,GIS,GM,GPC,GILD,GL,GPN,GS,GWW,HAL,HBI,HIG,HAS,HCA,PEAK,HSIC,HES,HLT,HOLX,HWM,HPQ,HUM,HBAN,HII,IEX,IDXX,INFO,
ITW,ILMN,INCY,IR,INTC,ICE,IBM,IFF,IP,IPG,INTU,ISRG,IVZ,IPGP,IQV,IRM,JKHY,J,JBHT,JD,JR,JCI,SJM,JNJ,JCI,JPM,JNPR,KSU,K,KEY,KEYS,KMB,KIM,
KMI,KLAC,KHC,KR,LHX,LH,LRCX,LW,LVS,LEG,LDOS,LEN,LLY,LNC,LLTC,LUMN,LYB,MTB,MAC,M,MRO,MPC,MKTX,MAR,MMC,MAS,MA,MTCH,MKC,MXIM,MCD,MCK,MDT,
MRK,MET,MTD,MGM,MCHP,MU,MSFT,MAA,MHK,TAP,MDLZ,MPWR,MNST,MCO,MS,MSI,MSCI,MYL,NDAQ,NOV,NKTR,NLOK,NCLH,NEE,NLSN,NKE,NI,NBL,NSC,NTRS,NOC,
NLOK,NCLH,NUE,NVDA,NXPI,ORLY,OXY,ODFL,OMC,OKE,ORCL,OTIS,PCAR,PKG,PARA,PAYX,PBCT,PYPL,PENN,PNC,PFG,PG,PGR,PLD,PRU,PEG,PSX,PNW,PXD,PEP,
PKI,PNR,RL,PPG,PPL,PFG,PM,PSA,PHM,PVH,QRVO,PWR,QCOM,DGX,RL,RJF,RTX,O,REG,REGN,RF,RSG,RMD,RHI,ROK,ROL,ROP,ROST,RCL,SPGI,CRM,SBAC,SLB,STX,
SEE,SRE,NOW,SHW,SPG,SWKS,SLG,SNA,SO,LUV,SPG,SWKS,SBUX
""")

# ---------------- Nasdaq-100 ----------------
NASDAQ100_LIST = _parse_blob("""
AAPL,MSFT,NVDA,GOOGL,GOOG,AMZN,AVGO,PEP,TSLA,ADBE,INTU,CSCO,CMCSA,ASML,CMCSA,TXN,QCOM,AMD,AMGN,NFLX,INTC,BIIB,ADP,BKNG,COST,AMD,ISRG,
ADSK,LRCX,KLAC,CSGP,IDXX,ILMN,MRVL,MU,ZM,MAR,ADP,CTSH,REGN,PYPL,VRTX,FISV,ADBE,EXC,DOCU,CRWD,SGEN,WDAY,KHC,CTAS,EA,EXEL,PDD,ZM,UAL,CHTR,
DXCM,DLTR,KYXY,XLNX,LULU,MNST,SBUX,ASML,SGEN,CPRT,CDNS,DLTR,DDOG,CME,DLTR,ROST,SIRI,ALI,PANW,CTXS,SNPS,ORLY,MELI,GH,EBAY,BIDU,EXC,KLAC,
ANSS,ALGN,ETSY,DOCU,PCAR,FTNT,FTNT,OKTA,SGMO,XEL,TTWO,NTES,ZTS,BIIB,SPLK,TEAM,EA,NXPI,WDAY
""")

# ---------------- Dow 30 ----------------
DOW30_LIST = _parse_blob("""
MMM,AXP,AMGN,AAPL,BA,CAT,CVX,CSCO,KO,DOW,GS,HD,HON,IBM,INTC,JNJ,JPM,MCD,MRK,MSFT,NKE,CRM,TRV,UNH,VZ,V,DIS,WMT,PG,AMZN,NVDA,SHW
""")